// No network or model calls. Rebuilds the derived runtime prompt, then checks package integrity.
const fs=require('fs'), path=require('path'), crypto=require('crypto');
const root=path.resolve(__dirname,'..');
const read=n=>fs.readFileSync(path.join(root,n),'utf8').replace(/^\uFEFF/,'');
const json=n=>JSON.parse(read(n));
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const checkOnly=process.argv.includes('--check');
const platform=process.argv.find(x=>x.startsWith('--platform='))?.split('=')[1];
if(!['GPT','Claude'].includes(platform)) throw new Error('Use --platform=GPT or --platform=Claude');
const entry='00_'+platform+'_系統提示.md';
const names=[entry,'directing.md','characters.json','pipeline.json'];
const texts=Object.fromEntries(names.map(n=>[n,read(n)]));
const c=json('characters.json'),p=json('pipeline.json');
const results=[];
function check(name,ok,detail=''){results.push({name,status:ok?'passed':'failed',detail});}
function skip(name,detail){results.push({name,status:'skipped',detail});}
check('角色與管線版本符合本次修改範圍',c._meta.version==='0.2.3'&&p._meta.version==='0.2.2');
check('53 項映射保留',Object.keys(c.character_name_zh_to_tag).length===53);
const old=json('維護資料/原版封存/characters.json').character_name_zh_to_tag;
check('原角色與系列 tag 未改',Object.entries(old).every(([n,e])=>c.character_name_zh_to_tag[n]?.character_tag===e.character_tag&&c.character_name_zh_to_tag[n]?.series_tag===e.series_tag));
const entries=Object.values(c.character_name_zh_to_tag);
check('每項有身份與非空 tag',entries.every(e=>e.identity_id&&e.character_tag&&e.series_tag));
check('44 個身份未意外合併',new Set(entries.map(e=>e.identity_id)).size===44);
const ids=new Set(entries.map(e=>e.identity_id));
check('身份限制無懸空引用',Object.keys(c.identity_policies).every(id=>ids.has(id)));
const base=c.character_name_zh_to_tag['三月七'],variant=c.character_name_zh_to_tag['三月七(巡獵)'];
check('三月七變體共用身份限制且保留變體 tag',base.identity_id===variant.identity_id&&base.character_tag!==variant.character_tag&&c.identity_policies[variant.identity_id]?.sexualization==='prohibited');
const normalize=s=>s.normalize('NFKC').toLowerCase().replace(/_/g,' ').replace(/\s/g,'');
const normalized=new Map();let collisions=[];
for(const [n,e] of Object.entries(c.character_name_zh_to_tag)) for(const candidate of [n,e.character_tag]){
 const k=normalize(candidate),prev=normalized.get(k);if(prev&&prev!==e.identity_id)collisions.push(candidate);normalized.set(k,e.identity_id);
}
check('正規化後無跨身份碰撞',collisions.length===0,collisions.join(','));
check('全形巡獵名稱可命中',normalized.get(normalize('三月七（巡獵）'))===variant.identity_id);
check('大黑塔與黑天鵝未合併',c.character_name_zh_to_tag['大黑塔'].identity_id!==c.character_name_zh_to_tag['黑天鵝'].identity_id);
check('watch 四項均不捏造原因',entries.filter(e=>e.watch).length===4&&entries.filter(e=>e.watch).every(e=>e.watch.cause==='unknown'));
const oldp=json('維護資料/原版封存/pipeline.json');
const pc=p.prompt_contract;
check('prefix 符合 v0.2.1 核准值',pc.positive_prefix==='masterpiece, best quality, score_7, {rating},');
check('prefix 不含官方體系外品質詞',!/very aesthetic|ultra detailed|high contrast/.test(pc.positive_prefix));
check('固定風格詞存在且位置已定義',pc.fixed_style_tags?.tags==='high contrast'&&!!pc.fixed_style_tags.placement);
check('負向 target 由 base、hands_feet_guard、skin_finish_guard 組成',pc.negative.target===[pc.negative.base,pc.negative.hands_feet_guard,pc.negative.skin_finish_guard].join(', '));
check('負向不含安全標籤',!/\b(nsfw|explicit|sensitive|safe)\b/.test(pc.negative.target));
check('負向單行且逗號後有空格',!/[\r\n]/.test(pc.negative.target)&&!/,\S/.test(pc.negative.target));
check('序列化規則含括號跳脫與權重政策',!!pc.serialization?.literal_parentheses&&!!pc.serialization?.weighting);
check('prefix 有且只有一個 rating 槽',(p.prompt_contract.positive_prefix.match(/\{rating\}/g)||[]).length===1);
check('rating 模式資料完整',Object.values(p.prompt_contract.rating_by_mode).every(m=>p.prompt_contract.rating_slot.allowed.includes(m.rating)&&Array.isArray(m.required_tags)));
check('非成人模式不常駐 adult',p.prompt_contract.rating_by_mode.safe.required_tags.length===0&&p.prompt_contract.rating_by_mode.sensitive.required_tags.length===0&&p.prompt_contract.rating_by_mode.adult.required_tags.includes('adult'));
const links=p.snapshot.links;
check('CLIP→LoRA→正負編碼鏈有快照支持',[[12,38],[38,14],[38,15],[14,31],[15,31]].every(([a,b])=>links.some(l=>l[1]===a&&l[3]===b)));
check('主模型與 LoRA 未改',p.snapshot.models.unet.name===oldp.models.unet.unet_name&&JSON.stringify(p.snapshot.loras.entries)===JSON.stringify(oldp.loras.entries));
check('尺寸及取樣參數未改',p.snapshot.latent.width===oldp.latent.width&&p.snapshot.latent.height===oldp.latent.height&&['steps','cfg','sampler_name','scheduler','denoise'].every(k=>p.snapshot.sampler[k]===oldp.sampler[k]));
const tok=s=>s.split(',').map(x=>x.trim()).filter(Boolean);
if(p.snapshot.prompts.negative_tokens_match_target===false) skip('快照負向依詞序與契約相符','快照早於 v0.2.1 契約，待使用者更新工作流並重新快照（V-007）');
else check('快照負向依詞序與契約相符',JSON.stringify(tok(p.snapshot.prompts.negative_node15))===JSON.stringify(tok(p.prompt_contract.negative.target)));
check('FaceDetailer 狀態一致',p.snapshot.main_face_detailer.active===(p.snapshot.main_face_detailer.mode===0));
check('D01–D08 各有唯一主章節',Array.from({length:8},(_,i)=>'D0'+(i+1)).every(id=>(texts['directing.md'].match(new RegExp('^## '+id+'｜','gm'))||[]).length===1));
const cases=json('驗收/模型測試案例.json');
check('測試 ID 唯一且有輸入與判準',new Set(cases.cases.map(x=>x.id)).size===cases.cases.length&&cases.cases.every(x=>x.turns.length&&x.assertions.length));
const modelLog=json('驗收/模型測試紀錄.json');
check('模型紀錄狀態有結果支持',modelLog.runs.length===0?modelLog.targets.every(t=>t.status==='NOT_RUN'):modelLog.runs.every(r=>r.case_id&&r.model_id&&r.responses?.length&&r.assertion_results?.length));
const sources=json('維護資料/source_manifest.json');
check('封存原檔雜湊一致',sources.files.every(x=>sha(fs.readFileSync(path.join(root,'維護資料','原版封存',x.name)))===x.sha256));
const originalAvailable=fs.existsSync(sources.source);
if(originalAvailable) check('原始來源未修改',sources.files.every(x=>sha(fs.readFileSync(path.join(sources.source,x.name)))===x.sha256),'外部來源可存取');
else skip('原始來源未修改','來源不在此電腦；僅上方封存雜湊檢查已執行');
check('冒煙涵蓋全部critical',cases.cases.filter(x=>x.severity==='critical').every(x=>cases.smoke_case_ids.includes(x.id)));
check('冒煙ID有效且唯一',new Set(cases.smoke_case_ids).size===cases.smoke_case_ids.length&&cases.smoke_case_ids.every(id=>cases.cases.some(x=>x.id===id)));
const out={checked_at:new Date().toISOString(),version:'0.2.6',scope:'專案資料及結構；不代表LLM或成圖通過',passed:results.filter(r=>r.status==='passed').length,failed:results.filter(r=>r.status==='failed').length,skipped:results.filter(r=>r.status==='skipped').length,total:results.length,results,source_hashes:Object.fromEntries(names.map(n=>[n,sha(texts[n])])),project_sha256:sha(JSON.stringify(texts)),model_execution_status:modelLog.runs.length?'SEE_MODEL_LOG':'NOT_RUN'};
fs.writeFileSync(path.join(root,'驗收',platform+'_靜態檢查結果.json'),JSON.stringify(out,null,2)+'\n','utf8');
console.log(JSON.stringify({platform,passed:out.passed,failed:out.failed,skipped:out.skipped,total:out.total,model_execution_status:out.model_execution_status}));
if(out.failed)process.exitCode=1;
